name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Windows Builder
        shell: cmd
        run: |
          cd build
          BUILD_WINDOWS.bat

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Thesis-Studio-Windows
          path: dist/**
